name: router_compiler
description: Flutter Router Compiler.
version: 2.0.0
homepage: https://github.com/LebranD/router_kit
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  router_annotation:
    path: ../router_annotation

  analyzer: ^5.13.0
  logging: ^1.0.1
  build: ^2.0.1
  source_gen: ^1.2.7
dev_dependencies:
  pedantic:

  json_serializable:
